# Generated by Django 5.1.5 on 2025-02-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shutter_payment', '0002_remove_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderpackage',
            old_name='quantity',
            new_name='number_of_copies',
        ),
        migrations.AddField(
            model_name='orderpackage',
            name='number_of_photos',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
